# Основные директории
input_dir: '..' # Родительская директория, в которой лежит папка со скриптом и видео для кодирования
output_dir: '../WATERMARKED' # Папка для видео с водяным знаком
no_wm_output_dir: '../ENCODED_NO_WM' # Папка для видео без водяного знака
ffmpeg_path: ./ff.exe

# Параметры водяного знака и описания
static_watermark: 'Ani4KHUB.png' # Файл водяного знака
description: 'Made by Ani4K HUB | t.me/ani4k_ru' # Описание, которое будет вшиваться в метаданные видео в поля description и title

# Выберите кодер: "av1_nvenc" или "hevc_nvenc"
encoder: "av1_nvenc"

# Настройки обработки
threshold_minutes: 40 # Лимит времени, при привышении которого будет рассчитываться целевой битрейт (Минут)
max_file_size_gb: 3.6 # Максимальный размер выходного файла (ГБ)
default_video_bitrate: 12000000 # Стандартный битрейт для видео, длина которых меньше, чем threshold_minutes (Мбит/с)
target_audio_bitrate: 256 # Битрейт, с которым будет закодирована аудиодорожка выходного видео (Кбит/с)
